### ISSUE TITLE
Testing party bugs

### ISSUE THREAD

**Issue by Shardhakoul** [gcivil-nyu-org/S2022-Team-4-repo#259]
Team 4-

1) As per point 1 in 'Users' By entering First Name, Last Name, Email, Gender and Password (which should meet requested format) and pressing the “Register” button. Upon successful registration it should take me to a page which asks me to verify my email and after successfully verifying my email it will be redirected

But I entered the password as django@100 and not able to register .I did the same with Django@100 and was able to register. I understand that you missed to mention that the password complexity should cover uppercase character and the same should be mentioned.
![image](https://user-images.githubusercontent.com/85691194/163725093-1d0952b7-16db-42d5-87da-d6d7c43beee1.png)

2) My profile has no image whereas the dropdown has an user image.
![image](https://user-images.githubusercontent.com/85691194/163725539-bbe208d1-7884-4a9d-b91f-b99c67073cd9.png)

3) On Page - Offer Services: Not able to create a service after entering the details and clicking submit
![image](https://user-images.githubusercontent.com/85691194/163725863-ed0aa06f-deda-47cd-bf2d-24fa8cc0e8f0.png)

4) In the Forums when Creating a post the timestamp is different(UTC)
![image](https://user-images.githubusercontent.com/85691194/163725977-98d4c394-b847-49fa-97c6-28fc385de0aa.png)

5)Developers images not visible
![image](https://user-images.githubusercontent.com/85691194/163726072-0b3bba5b-399c-4fe7-8026-7a46275734e9.png)

6) On clicking Report service or Not enough coins it is not redirecting to any page
![image](https://user-images.githubusercontent.com/85691194/163726313-67dc97ca-cfb1-4205-8f5f-ec38254b7aeb.png)

**Comment by srijanmalhotra2711** [comment]
1. Seems to have a **sessions issue**. I was logged in at 9 in the morning today and I am still logged in right now. Must work on auto-logout.

2. While I was creating a service I was able to see the use of an **unlicensed software**. That should not be the case.
